Week 1: 

**ReLU** - Rectified Linear Unit

**Dense Layer** - every input node is connected to every output node

**Applications of Deep Learning**
- Advertising - standard NN
- Image - CNN
- Audio - RNN because of temporal features
- Transalation - RNN
- Image, Radar Info - Custom / Hybrid

To get better performances we need to take advantage of few things
- train a bigger / larger model (computation)
- need a lot of data (labeled data)
- better algorithms

Switching from sigmoid to ReLU increased performance

Week 2:

Binary Classification - Logistic Regression

### Vectorization Example

In [55]:
import numpy as np

In [56]:
a = np.array([1,2,3,4])

In [57]:
a

array([1, 2, 3, 4])

In [58]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [59]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(f"Vectorized run time is {(toc - tic ) * 1000} ms ") 

Vectorized run time is 2.6292800903320312 ms 


In [60]:
c

250002.69811066572

In [61]:
c = 0
tic = time.time()

for i in range(len(a)):
    c += a[i]*b[i]
toc = time.time()
print(f"Non Vectorized run time is {(toc - tic ) * 1000} ms ") 

Non Vectorized run time is 667.186975479126 ms 


In [79]:
c

250002.69811066135

### More vectorization examples

In [71]:
v = np.random.randint(range(1,11))

In [72]:
v

array([0, 0, 2, 2, 3, 1, 0, 6, 4, 4])

In [78]:
np.maximum(v,1)

array([1, 1, 2, 2, 3, 1, 1, 6, 4, 4])

### More Examples

In [115]:
A = np.array([56.0, 0.0, 4.4,68.0,
    1.2,104.0,54.0,8,
    1.8,135,99,0.9])

In [116]:
A = A.reshape(3,4)
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  54. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [117]:
A = A *100 / A.sum(axis=0)
A

array([[94.91525424,  0.        ,  2.79542567, 88.42652796],
       [ 2.03389831, 43.51464435, 34.30749682, 10.40312094],
       [ 3.05084746, 56.48535565, 62.89707751,  1.17035111]])

### Tips and Tricks

In [143]:
a = np.random.randn(5)
a

array([-0.47382534,  0.55272035,  1.24937129, -0.3402488 , -0.54524565])

In [144]:
a.shape # this is neither row vector not column vector , it is called rank 1 array 

(5,)

In [145]:
a.T

array([-0.47382534,  0.55272035,  1.24937129, -0.3402488 , -0.54524565])

In [146]:
np.dot(a,a.T) # not we wanted 

2.5040009340185487

#### Instead use like this

In [147]:
b = np.random.randn(5,1)

In [148]:
b.shape # column vector

(5, 1)

In [149]:
b

array([[-1.0554056 ],
       [ 1.00135918],
       [ 0.26452126],
       [ 0.56145147],
       [ 0.66955922]])

In [150]:
b.T # correct transpose , row vector

array([[-1.0554056 ,  1.00135918,  0.26452126,  0.56145147,  0.66955922]])

In [151]:
np.dot(b,b.T)

array([[ 1.11388098, -1.05684008, -0.27917722, -0.59255902, -0.70665655],
       [-1.05684008,  1.0027202 ,  0.26488079,  0.56221458,  0.67046927],
       [-0.27917722,  0.26488079,  0.0699715 ,  0.14851585,  0.17711265],
       [-0.59255902,  0.56221458,  0.14851585,  0.31522775,  0.37592501],
       [-0.70665655,  0.67046927,  0.17711265,  0.37592501,  0.44830955]])

#### Use reshape to convert to either row or column vector

In [153]:
a

array([-0.47382534,  0.55272035,  1.24937129, -0.3402488 , -0.54524565])

In [154]:
a.reshape(5,1)

array([[-0.47382534],
       [ 0.55272035],
       [ 1.24937129],
       [-0.3402488 ],
       [-0.54524565]])

In [155]:
a.reshape(1,5) # notice the double bracket

array([[-0.47382534,  0.55272035,  1.24937129, -0.3402488 , -0.54524565]])

### Activation Functions

![activation fun](https://github.com/vipulrai91/dl-specialization/blob/master/resources/img/activation_functions.png)